---
title: paulywill
timezone: UTC
description: My test and development area for experiments and adventures.
baseurl: "/"
url: http://paulywill.com
github_username: paulywill
markdown: kramdown
theme: minima
plugins: 
